name:                ASE2
version:             0.1.0.0
github:              "rmcgouran/ASE2"
license:             BSD3
author:              "Ryan McGouran"
maintainer:          "ryane@mcgouran.co.uk"
copyright:           "2023 Ryan McGouran"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rmcgouran/ASE2/blob/main/README.md>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ASE2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ASE2

tests:
  ASE2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ASE2
    - HUnit
    - QuickCheck
    - random
    - hspec
